spring:
  application:
    name: eureka-discovery-server
server:
  port: 7783
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:7783/eureka/
